// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCar.Combinedstation.Infrastruchar;

#nullable disable

namespace TaxCar.Combinedstation.Infrastruchar.Migrations
{
    [DbContext(typeof(CombinedstationDBContext))]
    [Migration("20231026141513_Chack0")]
    partial class Chack0
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCar.Combinedstation.Core.CombinedStations", b =>
                {
                    b.Property<Guid>("CombinedStationsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CombinedStationsId");

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("CombinedStationsId")
                        .HasName("CombinedStationsId");

                    b.ToTable("CombinedStations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
