// <auto-generated />
using CarTax.Car.Infrastruchar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarTax.Car.Infrastruchar.Migrations
{
    [DbContext(typeof(CarDBContext))]
    [Migration("20231013151437_Chack")]
    partial class Chack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTax.Car.Domain.Cars", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("CarTypeId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("CarId");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("CarTax.Car.Domain.Cars", b =>
                {
                    b.OwnsOne("CarTax.Car.Domain.ValueObjects.Plack", "Plack", b1 =>
                        {
                            b1.Property<int>("CarsId")
                                .HasColumnType("integer");

                            b1.Property<string>("CodePlack")
                                .IsRequired()
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("CodePlack");

                            b1.Property<string>("NumberPlack")
                                .IsRequired()
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NumberPlack");

                            b1.HasKey("CarsId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarsId");
                        });

                    b.Navigation("Plack")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
