// <auto-generated />
using System;
using CarTax.Car.Infrastruchar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarTax.Car.Infrastruchar.Migrations
{
    [DbContext(typeof(CarDBContext))]
    [Migration("20231010145251_addBesT12")]
    partial class addBesT12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTax.Car.Domain.Entitys.CarType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("CarTypeId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTaxActive")
                        .HasColumnType("bit");

                    b.Property<string>("NameTypeCar")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("CarTypeId");

                    b.ToTable("CarTypes", (string)null);
                });

            modelBuilder.Entity("CarTax.Car.Domain.Root.Cars", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("CarTypeId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("CarId");

                    b.HasIndex("CarTypeId");

                    b.ToTable("Cars", (string)null);
                });

            modelBuilder.Entity("CarTax.Car.Domain.Root.Cars", b =>
                {
                    b.HasOne("CarTax.Car.Domain.Entitys.CarType", "CarType")
                        .WithMany("Cars")
                        .HasForeignKey("CarTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CarTax.Car.Domain.ValueObjects.Plack", "Plack", b1 =>
                        {
                            b1.Property<int>("CarsId")
                                .HasColumnType("int");

                            b1.Property<string>("CodePlack")
                                .IsRequired()
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("CodePlack");

                            b1.Property<string>("NumberPlack")
                                .IsRequired()
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("NumberPlack");

                            b1.HasKey("CarsId");

                            b1.ToTable("Cars");

                            b1.WithOwner()
                                .HasForeignKey("CarsId");
                        });

                    b.Navigation("CarType");

                    b.Navigation("Plack")
                        .IsRequired();
                });

            modelBuilder.Entity("CarTax.Car.Domain.Entitys.CarType", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
