// <auto-generated />
using System;
using CarTax.CarType.Infrastruchar;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarTax.CarType.Infrastruchar.Migrations
{
    [DbContext(typeof(CarTypeDBContext))]
    [Migration("20231012144005_Chack1")]
    partial class Chack1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarTax.CarType.Domain.CarTypes", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("CarTypeId");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsTaxActive")
                        .HasColumnType("bit");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("TypeCarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id")
                        .HasName("CarTypeId");

                    b.ToTable("CarTypes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
